CREATE TABLE IF NOT EXISTS PILL (
     id INT PRIMARY KEY AUTO_INCREMENT,
     ko_name TEXT NOT NULL,
     en_name TEXT NULL,
     image_url TEXT NULL,
     ingredient TEXT NULL,
     assortment TEXT NULL,
     unitariness_or_complexness TEXT NULL,
     manufacture_assortment TEXT NULL,
     seller TEXT NULL,
     formulation TEXT NULL,
     taking_route TEXT NULL,
     korea_food_and_drug_administration_category TEXT NULL,
     insurance_code TEXT NULL,
     combination_taboo TEXT NULL,
     age_taboo TEXT NULL,
     pregnant_taboo TEXT NULL,
     old_man_caution TEXT NULL,
     volume_and_treatment_period_caution TEXT NULL,
     division_caution TEXT NULL,
     blood_donation_prohibition TEXT NULL,
     shape_info TEXT NULL,
     packing_unit TEXT NULL,
     storagint_method TEXT NULL,
     efficacy TEXT NULL,
     dosage TEXT NULL,
     precaution TEXT NULL,
     medication_guide TEXT NULL
)DEFAULT CHARSET=utf8;